version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/auth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/services/vehicles"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/services/traffic"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/services/incidents"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/services/notifications"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/gateway"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
